version: '3'

services:
  server:
    restart: always
    build: ./server
    ports:
      - 8080:8080
    env_file:
      - ./server/config.env
    volumes:
      - ./wallets/dv.neo-wallet.json:/go/src/DigitalVerse/dv.neo-wallet.json
      - ./tests/test.mov:/go/src/DigitalVerse/videos/test.mov